project:
  type: website

website:
  title: "Ezra Spira-Cohen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications

format:
  html:
    theme:
      - cosmo


